# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: frr-northbound.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("frr-northbound.proto", :syntax => :proto3) do
    add_message "frr.GetCapabilitiesRequest" do
    end
    add_message "frr.GetCapabilitiesResponse" do
      optional :frr_version, :string, 1
      optional :rollback_support, :bool, 2
      repeated :supported_modules, :message, 3, "frr.ModuleData"
      repeated :supported_encodings, :enum, 4, "frr.Encoding"
    end
    add_message "frr.GetRequest" do
      optional :type, :enum, 1, "frr.GetRequest.DataType"
      optional :encoding, :enum, 2, "frr.Encoding"
      optional :with_defaults, :bool, 3
      repeated :path, :string, 4
    end
    add_enum "frr.GetRequest.DataType" do
      value :ALL, 0
      value :CONFIG, 1
      value :STATE, 2
    end
    add_message "frr.GetResponse" do
      optional :timestamp, :int64, 1
      optional :data, :message, 2, "frr.DataTree"
    end
    add_message "frr.CreateCandidateRequest" do
    end
    add_message "frr.CreateCandidateResponse" do
      optional :candidate_id, :uint32, 1
    end
    add_message "frr.DeleteCandidateRequest" do
      optional :candidate_id, :uint32, 1
    end
    add_message "frr.DeleteCandidateResponse" do
    end
    add_message "frr.UpdateCandidateRequest" do
      optional :candidate_id, :uint32, 1
    end
    add_message "frr.UpdateCandidateResponse" do
    end
    add_message "frr.EditCandidateRequest" do
      optional :candidate_id, :uint32, 1
      repeated :update, :message, 2, "frr.PathValue"
      repeated :delete, :message, 3, "frr.PathValue"
    end
    add_message "frr.EditCandidateResponse" do
    end
    add_message "frr.LoadToCandidateRequest" do
      optional :candidate_id, :uint32, 1
      optional :type, :enum, 2, "frr.LoadToCandidateRequest.LoadType"
      optional :config, :message, 3, "frr.DataTree"
    end
    add_enum "frr.LoadToCandidateRequest.LoadType" do
      value :MERGE, 0
      value :REPLACE, 1
    end
    add_message "frr.LoadToCandidateResponse" do
    end
    add_message "frr.CommitRequest" do
      optional :candidate_id, :uint32, 1
      optional :phase, :enum, 2, "frr.CommitRequest.Phase"
      optional :comment, :string, 3
    end
    add_enum "frr.CommitRequest.Phase" do
      value :VALIDATE, 0
      value :PREPARE, 1
      value :ABORT, 2
      value :APPLY, 3
      value :ALL, 4
    end
    add_message "frr.CommitResponse" do
      optional :transaction_id, :uint32, 1
    end
    add_message "frr.ListTransactionsRequest" do
    end
    add_message "frr.ListTransactionsResponse" do
      optional :id, :uint32, 1
      optional :client, :string, 2
      optional :date, :string, 3
      optional :comment, :string, 4
    end
    add_message "frr.GetTransactionRequest" do
      optional :transaction_id, :uint32, 1
      optional :encoding, :enum, 2, "frr.Encoding"
      optional :with_defaults, :bool, 3
    end
    add_message "frr.GetTransactionResponse" do
      optional :config, :message, 1, "frr.DataTree"
    end
    add_message "frr.LockConfigRequest" do
    end
    add_message "frr.LockConfigResponse" do
    end
    add_message "frr.UnlockConfigRequest" do
    end
    add_message "frr.UnlockConfigResponse" do
    end
    add_message "frr.ExecuteRequest" do
      optional :path, :string, 1
      repeated :input, :message, 2, "frr.PathValue"
    end
    add_message "frr.ExecuteResponse" do
      repeated :output, :message, 1, "frr.PathValue"
    end
    add_message "frr.ModuleData" do
      optional :name, :string, 1
      optional :organization, :string, 2
      optional :revision, :string, 3
    end
    add_message "frr.PathValue" do
      optional :path, :string, 1
      optional :value, :string, 2
    end
    add_message "frr.DataTree" do
      optional :encoding, :enum, 1, "frr.Encoding"
      optional :data, :string, 2
    end
    add_enum "frr.Encoding" do
      value :JSON, 0
      value :XML, 1
    end
  end
end

module Frr
  GetCapabilitiesRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("frr.GetCapabilitiesRequest").msgclass
  GetCapabilitiesResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("frr.GetCapabilitiesResponse").msgclass
  GetRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("frr.GetRequest").msgclass
  GetRequest::DataType = Google::Protobuf::DescriptorPool.generated_pool.lookup("frr.GetRequest.DataType").enummodule
  GetResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("frr.GetResponse").msgclass
  CreateCandidateRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("frr.CreateCandidateRequest").msgclass
  CreateCandidateResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("frr.CreateCandidateResponse").msgclass
  DeleteCandidateRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("frr.DeleteCandidateRequest").msgclass
  DeleteCandidateResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("frr.DeleteCandidateResponse").msgclass
  UpdateCandidateRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("frr.UpdateCandidateRequest").msgclass
  UpdateCandidateResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("frr.UpdateCandidateResponse").msgclass
  EditCandidateRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("frr.EditCandidateRequest").msgclass
  EditCandidateResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("frr.EditCandidateResponse").msgclass
  LoadToCandidateRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("frr.LoadToCandidateRequest").msgclass
  LoadToCandidateRequest::LoadType = Google::Protobuf::DescriptorPool.generated_pool.lookup("frr.LoadToCandidateRequest.LoadType").enummodule
  LoadToCandidateResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("frr.LoadToCandidateResponse").msgclass
  CommitRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("frr.CommitRequest").msgclass
  CommitRequest::Phase = Google::Protobuf::DescriptorPool.generated_pool.lookup("frr.CommitRequest.Phase").enummodule
  CommitResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("frr.CommitResponse").msgclass
  ListTransactionsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("frr.ListTransactionsRequest").msgclass
  ListTransactionsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("frr.ListTransactionsResponse").msgclass
  GetTransactionRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("frr.GetTransactionRequest").msgclass
  GetTransactionResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("frr.GetTransactionResponse").msgclass
  LockConfigRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("frr.LockConfigRequest").msgclass
  LockConfigResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("frr.LockConfigResponse").msgclass
  UnlockConfigRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("frr.UnlockConfigRequest").msgclass
  UnlockConfigResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("frr.UnlockConfigResponse").msgclass
  ExecuteRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("frr.ExecuteRequest").msgclass
  ExecuteResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("frr.ExecuteResponse").msgclass
  ModuleData = Google::Protobuf::DescriptorPool.generated_pool.lookup("frr.ModuleData").msgclass
  PathValue = Google::Protobuf::DescriptorPool.generated_pool.lookup("frr.PathValue").msgclass
  DataTree = Google::Protobuf::DescriptorPool.generated_pool.lookup("frr.DataTree").msgclass
  Encoding = Google::Protobuf::DescriptorPool.generated_pool.lookup("frr.Encoding").enummodule
end
